<a href="https://colab.research.google.com/github/LIMJIALIH/WIA1007/blob/main/Tutorial%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
        ##Tutorial 2
#import numpy as np
#import pandas as pd

#arr = np.array([[1,2],[3,4]])
#print(arr)

#randArr = np.random.rand(3,4)
#print(f'\n{randArr}')

#arrOne = np.ones((4,2))
#print(f'\n{arrOne}')

#arrZero = np.zeros((4,2))
#print(f'\n{arrZero}')

#newArray = np.random.rand(6,3)
#print(f'\n{newArray}')
#arrTrans = newArray.T
#print(f'\n{arrTrans}')

#arr1 = np.random.rand(3,2)
#arr2 = np.random.rand(2,3)
#dotProduct = arr1.dot(arr2)
#print(f'\n{dotProduct}')


[[0.08479523 0.61601775 0.73198958]
 [0.09721656 0.32096406 0.36373859]
 [0.67194452 0.93541895 0.93074917]]
